backend:
  name: git-gateway
  repo: riofauzi708/riofauzi708.github.io
  branch: main

media_folder: "public/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/content/blog"
    extension: "md"
    format: "frontmatter"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Publish Date", name: "pubDate", widget: "datetime" }
      - { label: "Hero Image", name: "heroImage", widget: "image" }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "projects"
    label: "Projects"
    folder: "src/content/projects"
    extension: "md"
    format: "frontmatter"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Short Description", name: "description", widget: "text" }
      - { label: "Publish Date", name: "pubDate", widget: "datetime" }
      - { label: "Thumbnail Image", name: "heroImage", widget: "image" }

      - label: "Project Type"
        name: "projectType"
        widget: "select"
        options: ["Personal", "Team"]
        default: "Personal"

      - label: "Tech Stack"
        name: "techStack"
        widget: "list"
        field: { label: "Tech", name: "tech", widget: "string" }

      - label: "Live URL"
        name: "liveUrl"
        widget: "string"
        required: false

      - label: "Source Code"
        name: "sourceUrl"
        widget: "string"
        required: false

      - label: "Body"
        name: "body"
        widget: "markdown"
