backend:
  name: git-gateway
  repo: riofauzi708/riofauzi708.github.io
  branch: main

media_folder: "public/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "docs"
    label: "Docs"
    folder: "src/content/docs"
    extension: "md"
    format: "frontmatter"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string", required: true }
      - { label: "Description", name: "description", widget: "text", required: true }
      - { label: "Publish Date", name: "pubDate", widget: "datetime" }
      - { label: "Updated Date", name: "updatedDate", widget: "datetime", required: false }
      - { label: "Hero Image", name: "heroImage", widget: "image", required: false }
      - label: "Tags"
        name: "tags"
        widget: "list"
        field: { label: "Tag", name: "tag", widget: "string" }
      - label: "Draft"
        name: "draft"
        widget: "boolean"
        default: false
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "projects"
    label: "Projects"
    folder: "src/content/projects"
    extension: "md"
    format: "frontmatter"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string", required: true }
      - { label: "Short Description", name: "description", widget: "text", required: true }
      - { label: "Publish Date", name: "pubDate", widget: "datetime" }
      - { label: "Thumbnail Image", name: "heroImage", widget: "image", required: false }
      - label: "Project Type"
        name: "projectType"
        widget: "select"
        options: ["Personal", "Team"]
        default: "Personal"
      - label: "Platform"
        name: "platform"
        widget: "select"
        options: ["Mobile", "Website", "Other"]
        default: "Website"
      - label: "Tech Stack"
        name: "techStack"
        widget: "list"
        allow_add: true
        field: { label: "Tech", name: "tech", widget: "string" }
      - label: "Live URL"
        name: "liveUrl"
        widget: "string"
        required: false
      - label: "Source Code"
        name: "sourceUrl"
        widget: "string"
        required: false
      - label: "Draft"
        name: "draft"
        widget: "boolean"
        default: false
      - { label: "Body", name: "body", widget: "markdown" }
